### PR TITLE
Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by Mikeliro**

### CODE REVIEW

**Comment by cech12** [comment]
Thanks for your pull request. One question is open for me: Is "Aréola" the correct translation for halo? Isn't "Auréola" or "Nimbo" a better translation?

**Comment by Mikeliro** [comment]
Sorry the correct one is "Auréola"
I already fixed the error

**Comment by cech12** [comment]
Ok thanks, I will merge it. The changes will be part of the next version. :)

**Comment by cech12** [comment]
I like the colors. :D I added them also to the english language file ;)

**Pull request merged**
